job_roles = [
    {'role_title': 'Software Developer', 'query': 'Software (Developer OR Engineer)'},
    {'role_title': 'Frontend Developer', 'query': '(Frontend OR Front-End) (Developer OR Engineer)'},
    {'role_title': 'Backend Developer', 'query': '(Backend OR Back-End OR Server-side) (Developer OR Engineer)'},
    {'role_title': 'Fullstack Developer', 'query': '(Full-Stack OR Fullstack) (Developer OR Engineer)'},
    {'role_title': 'Mobile Developer', 'query': '(Mobile OR iOS OR Android) (Developer OR Engineer)'},
    {'role_title': 'Game Developer', 'query': '(Game OR Gaming OR Video-Game) (Developer OR Engineer)'},
    {'role_title': 'Data Scientist', 'query': 'Data (Scientist OR Analyst OR Engineer)'},
    {'role_title': 'ML/AI Developer', 'query': '(Machine-Learning OR ML OR AI OR Artificial-Intelligence) (Engineer OR Specialist OR Developer)'},
    {'role_title': 'DevOps Engineer', 'query': '(DevOps OR SRE) Engineer'},
    {'role_title': 'System/Network Engineer', 'query': '(System OR Network) Engineer'},
    {'role_title': 'Security Engineer', 'query': '(Cyber OR Information) Security (Engineer OR Analyst OR Specialist OR Consultant OR Manager)'},
    {'role_title': 'DBA', 'query': 'Database Administrator OR DBA'},
    {'role_title': 'Quality Assurance', 'query': '(QA OR Quality-Assurance) (Engineer OR Analyst OR Tester)'},
    {'role_title': 'UX/UI Designer', 'query': '(UX OR UI OR User-Experience OR User-Interface) Designer'}, {'role_title': 'System Admin', 'query': 'System Administrator'},
    {'role_title': 'Network Admin', 'query': 'Network Administrator'},
    {'role_title': 'Cloud Architect', 'query': '(Cloud OR AWS OR Azure OR Google Cloud) Architect'},
    {'role_title': 'Firmware/Embedded Developer', 'query': '(Firmware OR Embedded Systems) (Engineer OR Developer)'},
    {'role_title': 'Solution/Enterprise Developer', 'query': '(Solution OR Enterprise) (Architect OR Developer OR Engineer)'}]