languages = ['Scala', 'Clojure', 'Lua', 'Objective-C', 'Bash', 'Swift', 'Dart', 'Ruby', 'JavaScript', 'C#',
             'Powershell', 'HTML', 'Rust', 'Julia', 'Haskell', 'C++', 'SQL', 'Kotlin', 'Elixir', 'Assembly', 'C', 'PHP',
             'ARM', 'HTML/CSS', 'Erlang', 'Go', 'Python', 'Node.js', 'Java', 'Perl', 'CSS', 'GLSL', 'TypeScript', 'F#',
             'R', 'MATLAB', 'Groovy', 'Shell']

libraries = ['ASP.NET', 'jQuery', 'RxJS', 'NLTK', 'PyTorch', 'Semantic UI', 'Less', 'TensorFlow', 'Chai', 'Jasmine',
             'Heroicons', 'Material UI', 'Rollup.js', 'MobX', 'React Spring', 'Laravel', 'Prettier', 'Phaser',
             'Stencil', 'Puppeteer', 'stylelint', 'Rails', 'Django Rest Framework', 'Quasar', 'OpenGL', 'Pug',
             'Reactstrap', 'D3', 'React Bootstrap', 'NumPy', 'Webpack', 'Gatsby', 'Seaborn', 'Keras', 'Kubeflow',
             'PlayCanvas', 'FastAPI', 'Apollo', 'wxWidgets', 'SASS', 'Stylus', 'Foundation', 'Recoil', 'Sidekiq',
             'Electron', 'CMake', 'Plotly', 'Bulma', 'OpenCV', 'Scikit-Learn', 'Sass/SCSS', 'Lottie', 'React',
             'React Native', 'Unity UI', 'Box2D', 'PyTest', 'Angular', 'HAML', 'Web Components', 'Ant Design', 'ESLint',
             'GreenSock (GSAP)', 'Sequelize', 'CatBoost', 'Aphrodite', 'Bootstrap', 'Tailwind CSS', 'AngularJS',
             'Fabric', 'XGBoost', 'Radium', 'NestJS', 'react-testing-library', 'Redux', 'XML', 'Material Icons',
             'ReactiveX', 'UIKit', 'iOS SDK', 'spaCy', 'LitElement', 'Enzyme', 'Sails.js', 'Beautiful Soup',
             'StatsModels', 'Cordova', 'JSON', 'OpenNLP', 'Lodash', 'Three.js', 'Framer', 'Feast', 'Svelte',
             'Pandas Testing', 'Neo4j', 'Chainer', 'Caffe', 'Framer Motion', 'FontAwesome', 'Celery', 'Scrapy',
             'Matplotlib', 'TensorBoard', 'SciPy', 'Styled Components', 'ggplot2', 'Emotion', 'Lerna', 'CoreNLP',
             'Chakra UI', 'p5js', 'Pygame', 'OpenAI Gym', 'BeautifulSoup', 'Spring Boot', 'Flask', 'PyQt', 'PIL',
             'Jinja2', 'Socket.IO', 'A-frame', 'Django', 'Vue.js', 'Numpy', 'PostgreSQL', 'Tensorflow.js',
             'Scikit-image', 'Pymongo', 'SQLAlchemy', 'Qt', 'PySpark', 'Tkinter', 'Kivy', 'Requests', 'Dash',
             'Flask-SQLAlchemy', 'Flask-WTF', 'WebGL', 'gRPC', 'PostCSS', 'Vuetify', 'Vue', 'VuePress', 'rxjava', 'Babel']

tools = ['Airflow', 'Pytest', 'Postman', 'Vault', 'Lucidchart', 'Insomnia', 'Lighthouse', 'Adobe FrameMaker', 'Next.js',
         'Varnish', 'Kafka', 'BigQuery', 'MadCap Flare', 'Jira', 'BitBucket', 'MLflow', 'VXLAN', 'JTAG',
         'Logic Analyzers', 'PostgreSQL', 'WebSockets', 'Extent Reports', 'Android Studio', 'Apache Kafka',
         'Android SDK', 'Logstash', 'Yarn Workspaces', 'Theme UI', 'Kinesis', 'Container Registry',
         'Azure ExpressRoute', 'CodeCommit', 'Chef', 'Socket.IO', 'Sentry', 'GameMaker', 'Sketch', 'Splunk', 'KeyVault',
         'Config', 'Crashlytics', 'Cocoa', 'Glacier', 'Route53', 'HLSL', 'Proto.io', 'Apache Superset', 'VS Code',
         'Gatling', 'Solarwinds', 'Amplitude', 'Bokeh', 'CodePush', 'DVC', 'faker', 'Git', 'New Relic',
         'CI/CD Pipelines', 'Nessus', 'WKWebView', 'IntelliJ IDEA', 'Spine', 'Visio', 'SOAP', 'Rider', 'NativeScript',
         'AppDynamics', 'UML', 'Kibana', 'Hotjar', 'WebAssembly', 'Amundsen', 'JMeter', 'SIEM', 'Bitbucket',
         'Memcached', 'PowerShell', 'Packer', 'TestRail', 'Bugzilla', 'SQL Server', 'Azure IoT', 'EBS', 'Graylog',
         'Zeplin', 'Logging', 'SQS', 'Nagios', 'OWASP ZAP', 'MySQL', 'Playwright', 'AutoKeras', 'GitHub Actions',
         'Gradle', 'PWA', 'Express', 'IcoMoon', 'InVision', 'Looker', 'Mixpanel', 'Elasticsearch', 'SMTP', 'Allure',
         'Cypress', 'RabbitMQ', 'USB', 'FTP', 'Alibi', 'Capacitor', 'Asterisk', 'Bitrise', 'Microsoft SQL Server',
         'Locust', 'MIRO', 'Bash Scripting', 'Datadog', 'Eclipse', 'ReportPortal', 'Serenity BDD', 'Xcode', 'Prefect',
         'FreeSWITCH', 'FMOD', 'Storybook', 'InfluxDb', 'Draw.io', 'Gridsome', 'Hyper-V', 'Prometheus', 'Consul',
         'CodePipeline', 'Maven', 'Parcel', 'Spark MLlib', 'Puppet', 'Kerberos', 'Pulumi', 'Expo', 'Pandas', 'Nuxt.js',
         'Salt', 'Excel', 'dbt', 'Robot Framework', 'Azure Pipelines', 'NVDA', 'Principle', 'Keychain', 'k6',
         'Vue Router', 'Asana', 'Tableau', 'GitLab', 'Burp Suite', 'Yarn', 'Wireshark', 'SaltStack', 'Cloud VPN',
         'Flink', 'Jenkins', 'GitHub', 'Bamboo', 'AVR', 'Modbus', 'QEMU', 'TalkBack', 'IPSec', 'JWT', 'FreeRTOS',
         'CouchDB', 'Qt', 'Grafana', 'Mocha', 'OSSEC', 'Nmap', 'CodeBuild', 'CloudKit', 'GraphQL', 'Serverless',
         'Metasploit', 'Sass', 'Pylint', 'Qiskit', 'Exchange', 'SSH', 'Spring', 'Slack', 'S3', 'Cloudfront','ExpressRoute',
         'Ansible', 'Cisco ACI', 'JAWS', 'Pure.css', 'Snort', 'Lambda', 'Terraform', 'Kong', 'Meson', 'XCTest',
         'tcpdump', 'AKS', 'Hibernate', 'Kubeflow Pipelines', 'PhysX', 'HTTP/2', 'EFS', 'Visual Studio', 'Codec',
         'Trello', 'Firebase', 'Arduino', 'AWS Redshift', 'Redis', 'Sandboxing', 'SharePoint', 'Havok',
         'Cloud Functions', 'Red Hat', 'npm', 'NLB', 'GCC', 'Selenium', 'VPNs', 'NSX', 'gtest', 'GuardDuty', 'RuboCop',
         'InVision Inspect', 'Fastlane', 'Power BI', 'CircleCI', 'Cirq', 'Framer', 'Debuggers', 'Snowflake', 'Perforce',
         'Cocos2D', 'CloudTrail', 'Cg', 'Confluence', 'Google Analytics', 'Figma', 'SwiftUI', 'Figma Tokens',
         'Oracle Cloud', 'Appium', 'Emacs', 'EKS', 'Virtual Networks', 'Jetpack Compose', 'H2O AutoML', 'Verilator',
         'Yellowbrick', 'Nomad', 'Tecton', 'Unity', 'Zabbix', 'AutoGluon', 'JIRA', 'Azure DevOps', 'Apache Bench',
         'Buefy', 'SageMaker', 'Kafka Streams', 'JUnit', 'MongoDB', 'Version Control', 'Avocode', 'TestNG', 'WinForms',
         'Vim', 'Godot', 'Great Expectations', 'Photoshop', 'PRTG', 'Adobe XD', 'Jest', 'UI Automator', 'PyCharm',
         'CodeDeploy', 'Ionic', 'React Router', 'ELK Stack', 'DataHub', 'SQLite', 'EC2', 'Unity Test Runner', 'Rancher',
         'Illustrator', 'Xamarin', 'Gulp', 'SimpleCV', 'Nginx', 'DragonBones', 'CloudFormation', 'IBM Cloud', 'webpack',
         'PIL/Pillow', 'Azure SQL']

platforms = ['App Engine', 'AWS', 'OpenStack', 'FreeBSD', 'macOS', 'ARM Mbed', 'SNS', 'DigitalOcean', 'CosmosDB',
             'Embedded Linux', 'Azure', 'UNet', 'Linux', 'Android', 'VMware Cloud', 'ELK', 'Spark', 'Cosmos DB',
             'Android', 'RIOT OS', 'VMware', 'Windows', 'IAP', 'VPC', 'SaaS', 'Oracle', '802.15.4', 'BLE', 'Xen',
             'OLAP', 'BigTable', 'Helm','AWS IoT', 'DAS', 'PaaS', 'Google IoT Core', 'Azure IoT', 'SQL Server', 'RDS',
             'Docker', 'Flutter', 'HAProxy', 'Apache Airflow', 'Renode', 'NoSQL', 'GCP', 'OLTP', 'Unreal Engine',
             'Node', 'DynamoDB', 'Google Cloud Functions', 'Kubernetes', 'Lumberyard', 'AWS Transit Gateway', 'KVM',
             'Hopsworks', 'Alibaba Cloud', 'App Store', 'Azure Data Factory', 'Aurora', 'dagger.io','KMS', 'Windows IoT',
             'Amazon Lumberyard', 'Cloud Run', 'CloudWatch', 'Oculus SDK', 'IaaS', 'Ruby on Rails', 'Google VR', 'ECR',
             'Zephyr RTOS', 'PowerPC', 'Security Center', 'DocumentDB', 'HDFS', 'Play Store', 'Lightsail', 'Atlas',
             'CEPH', 'Argo', 'AD', 'Ubuntu', 'FaunaDB', 'IAM', 'Multi-Cloud', 'Storage Accounts', 'Relational DBs',
             'Word', 'DoDAF', 'Abstract', 'AliCloud', 'Amazon FreeRTOS', 'Apache', 'Kali Linux', 'Redis', 'Netflow',
             'VoIP', 'Threat Hunting', 'InfluxDB', 'Principle of Least Privilege', 'Cassandra', 'CentOS',
             'Raspberry Pi', 'Istio', 'Load Balancers', 'Azure DevOps', 'iOS', 'RISC-V']

methodologies = ['Card Sorting', 'SOA', 'Event-Driven Architecture', 'User Stories', 'Atomic Design',
                 'Object-Oriented Design', 'User Acceptance Testing', 'Infrastructure as Code', 'Type Systems', 'MVVM',
                 'Style Guides', 'Use Cases', 'Algorithms', 'Memory Management', 'Source Control', 'OOP',
                 'Documentation', 'SOLID Principles', 'Testing', 'Cloud Architecture', 'Reactive',
                 'JAMStack', 'Web Performance', 'Continuous Integration', 'Goal-Oriented Action Planning', 'Functional',
                 'DevOps', 'Scrum', 'Entity Relationship Diagrams', 'Safety Standards', 'Cryptography',
                 'Configuration Management', 'SEO', 'Unit Testing', 'WebRTC', 'REST APIs', 'Risk Management', 'TOGAF',
                 'TCP/IP', 'Business Continuity Planning', 'UI/UX Design', 'BDD', 'Task Scheduling',
                 'Usability Testing', 'App Optimization', 'Requirements Analysis', 'Log Analytics', 'Debugging',
                 'A/B Testing', 'Tracing', 'Presentation Skills', 'Normalization', 'Stakeholder Management', 'Agile',
                 'Data Structures', 'Accessibility', 'Scalability', 'CI/CD', 'State Management', 'GDPR',
                 'Data Modeling', 'Monitoring', 'Design Patterns', 'Data Warehousing', 'REST', 'Encryption',
                 'Exploratory Testing', 'Event-Driven', 'OAuth', 'Domain-Driven Design', 'Zero Trust',
                 'Functional Programming', 'Automation', 'Microservices',  'Integration Testing',
                 'automated deployments', 'Compliance', 'Query Tuning', 'ETL', 'TDD', 'Waterfall Model', 'Kanban',
                 'Lean Development', 'Pair Programming', 'Mob Programming', 'Code Review', 'Refactoring',
                 'Software Prototyping', 'Sprint Planning', 'Release Management', 'Incident Management',
                 'Problem Management', 'Service Level Management', 'ITIL', 'COBIT', 'Six Sigma']
